[psql]
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  dbname = "finances-dev"
  schema = "finances"
  blacklist = ["schema_migrations"]
  sslmode = "disable"

#  hostname: localhost
#  port: 5432
#  username: postgres
#  password: postgres
#  database: finances-dev
#  schema: finances
