AllCops:
  TargetRubyVersion: 2.6.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

require:
  - rubocop/rspec/focused

Bundler/OrderedGems:
  Enabled: false

Rails:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentArray:
  EnforcedStyle: consistent

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NilComparison:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/NumericPredicate:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RescueModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Alias:
  Enabled: false

Metrics:
  Enabled: false
